name: ❓ Question
description: "Submit a question"
title: "❓ Question:"
labels: [question]
body:
  - type: textarea
    id: feature-description
    validations:
      required: true
    attributes:
      label: "🙋‍♂️ Question"
      description: "A clear question. Please provide as much detail as possible."
      placeholder: "How do I ...?"
  - type: markdown
    attributes:
      value: |
        Before submitting, please check if the question hasn't been asked before.
